export const vendorCsvDayFields = [
  { dayOfWeek: 0, key: "monday", label: "Monday" },
  { dayOfWeek: 1, key: "tuesday", label: "Tuesday" },
  { dayOfWeek: 2, key: "wednesday", label: "Wednesday" },
  { dayOfWeek: 3, key: "thursday", label: "Thursday" },
  { dayOfWeek: 4, key: "friday", label: "Friday" },
  { dayOfWeek: 5, key: "saturday", label: "Saturday" },
  { dayOfWeek: 6, key: "sunday", label: "Sunday" },
] as const;

export const vendorCsvDishSlots = [1, 2] as const;
export const vendorCsvImageSlots = [1, 2] as const;

export const vendorCsvTemplateHeaders = [
  "vendor_name",
  "slug",
  "category",
  "price_band",
  "description",
  "phone",
  "address",
  "area",
  "city",
  "state",
  "country",
  "latitude",
  "longitude",
  "is_active",
  ...vendorCsvDayFields.flatMap(({ key }) => [`${key}_open`, `${key}_close`]),
  ...vendorCsvDishSlots.flatMap((slot) => [
    `dish_${slot}_name`,
    `dish_${slot}_description`,
    `dish_${slot}_image_url`,
  ]),
  ...vendorCsvImageSlots.flatMap((slot) => [
    `image_url_${slot}`,
    `image_sort_order_${slot}`,
  ]),
] as const;

export const vendorCsvTemplateRows = [
  [
    "Mama Put Rice",
    "",
    "rice",
    "budget",
    "Budget rice and stew spot for lunch rush orders.",
    "+2348000000000",
    "14 Aminu Kano Crescent, Wuse 2, Abuja",
    "Wuse 2",
    "Abuja",
    "FCT",
    "Nigeria",
    "9.0765",
    "7.3986",
    "true",
    "8 AM",
    "8 PM",
    "8 AM",
    "8 PM",
    "8 AM",
    "8 PM",
    "8 AM",
    "8 PM",
    "8 AM",
    "9 PM",
    "9 AM",
    "9 PM",
    "10 AM",
    "6 PM",
    "Jollof Rice Bowl",
    "Jollof rice with beef and plantain.",
    "https://images.example.com/jollof-rice-bowl.jpg",
    "Chicken Suya Combo",
    "Grilled chicken with suya spice and fries.",
    "https://images.example.com/chicken-suya-combo.jpg",
    "https://images.example.com/mama-put-front.jpg",
    "0",
    "https://images.example.com/mama-put-counter.jpg",
    "1",
  ],
] as const;
